service: myserverlessproject3

provider:
    name: aws
    runtime: nodejs12.x
    profile: serverlessuser
    region: eu-west-1
    stage: dev
    environment:
        bucketName: ${self:custom.bucketName}
        imageUploadBucket: ${self:custom.imageUploadBucket}
        region: us-east-1
    iamRoleStatements:
        - Effect: Allow
          Action:
              - s3:*
          Resource: '*'

plugins:
  - serverless-package-external

package:
    individually: true

custom:
  packageExternal:
    external:
      - '../s3'
  bucketName: buying-labs-bucket
  imageUploadBucket: buying-labs-bucket

functions:
    imageResize:
        handler: lambdas/endpoints/imageResize.handler
        events:
            - s3:
                  bucket: buying-labs-bucket
                  event: s3:ObjectCreated:*
                  rules:
                      - prefix: uploads/
                  existing: true

